const gatewayConfigs = {
  pagciwallet: {
    name: 'PagCi Wallet',
    baseUrl: 'https://api.pagci.com.br',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/v1/cobranca/pix', checkCharge: '/v1/cobranca/{id}' },
    bodyTemplate: ({ amount, description, customerName }) => ({
      valor: Math.round(amount * 100),
      descricao: description,
      pagador: { nome: customerName || 'Cliente' },
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qrCodeBase64', qrCodeText: 'codigoCopiaECola', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  pushinpay: {
    name: 'PushinPay',
    baseUrl: 'https://api.pushinpay.com.br/api',
    auth: 'bearer',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cashIn', checkCharge: '/transaction/{id}' },
    bodyTemplate: ({ amount, webhookUrl }) => ({
      value: Math.round(amount * 100),
      ...(webhookUrl ? { webhook_url: webhookUrl } : {}),
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['token'],
  },
  syncpay: {
    name: 'SyncPay',
    baseUrl: 'https://api.syncpay.com.br',
    auth: 'oauth2',
    authTokenUrl: '/api/partner/v1/auth-token',
    amountUnit: 'cents',
    endpoints: { createCharge: '/api/partner/v1/cashin', checkCharge: '/api/partner/v1/transaction/{id}' },
    bodyTemplate: ({ amount, description, customerName, customerEmail, webhookUrl, pixKey }) => ({
      ip: '127.0.0.1',
      pix: { expiresInDays: '2' },
      items: [{ title: description || 'Produto', quantity: 1, tangible: false, unitPrice: Math.round(amount * 100) }],
      amount: Math.round(amount * 100),
      customer: {
        name: customerName || 'Cliente',
        email: customerEmail || 'cliente@email.com',
        cpf: '00000000000',
        phone: '11999999999',
        externaRef: 'REF001',
        address: { city: 'Sao Paulo', state: 'SP', street: 'Rua', country: 'BR', zipCode: '00000000', complement: '', neighborhood: 'Centro', streetNumber: '0' },
      },
      metadata: { provider: 'zeze', sell_url: '', order_url: '', user_email: customerEmail || '', user_identitication_number: '' },
      traceable: false,
      postbackUrl: webhookUrl || '',
    }),
    responseMapping: { paymentId: 'idTransaction', qrCodeDataUrl: 'paymentCodeBase64', qrCodeText: 'paymentCode', status: 'status_transaction' },
    credentials: ['clientId', 'clientSecret'],
  },
  oasyfy: {
    name: 'Oasyfy',
    baseUrl: 'https://app.oasyfy.com/api/v1',
    auth: 'apikey',
    apiKeyHeader: 'x-public-key',
    amountUnit: 'cents',
    endpoints: { createCharge: '/receber-pix', checkCharge: '/buscar-transacao/{id}' },
    bodyTemplate: ({ amount, description, customerName }) => ({
      valor: Math.round(amount * 100),
      descricao: description,
      cliente: { nome: customerName || 'Cliente' },
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey', 'secretKey'],
  },
  vizzionpay: {
    name: 'VizzionPay',
    baseUrl: 'https://api.vizzionpay.com.br/v1',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount, description }) => ({ valor: Math.round(amount * 100), descricao: description }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  omegapay: {
    name: 'OmegaPay',
    baseUrl: 'https://api.omegapay.com/v1',
    auth: 'apikey',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/charge', checkCharge: '/pix/charge/{id}' },
    bodyTemplate: ({ amount }) => ({ amount: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'charge_id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey', 'secretKey'],
  },
  sigilopay: {
    name: 'SigiloPay',
    baseUrl: 'https://app.sigilopay.com.br/api/v1',
    auth: 'custom',
    customAuth: {
      headers: { 'x-public-key': '{publicKey}', 'x-secret-key': '{secretKey}' },
      fields: ['publicKey', 'secretKey'],
    },
    amountUnit: 'real',
    endpoints: { createCharge: '/gateway/pix/receive', checkCharge: '/gateway/transactions' },
    createMethod: 'POST',
    checkMethod: 'POST',
    bodyTemplate: ({ amount, identifier, client, callbackUrl }) => ({
      identifier: identifier || ('zeze_' + Date.now()),
      amount: amount,
      client: {
        name: (client?.name) || 'Cliente Zeze',
        email: (client?.email) || 'cliente@email.com',
        phone: (client?.phone) || '00000000000',
        document: (client?.document) || '00000000000',
      },
      ...(callbackUrl ? { callbackUrl } : {}),
    }),
    checkBodyTemplate: ({ transactionId }) => ({
      transactionId: transactionId,
    }),
    responseMapping: {
      paymentId: 'transactionId',
      qrCodeDataUrl: 'pix.base64',
      qrCodeText: 'pix.code',
      status: 'status',
    },
    credentials: ['publicKey', 'secretKey'],
  },
  paradise: {
    name: 'Paradise',
    baseUrl: 'https://api.paradise-pay.com/v1',
    auth: 'bearer',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/create', checkCharge: '/pix/{id}' },
    bodyTemplate: ({ amount, description }) => ({ amount: Math.round(amount * 100), description }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['token'],
  },
  hoopay: {
    name: 'HooPay',
    baseUrl: 'https://hoopaywallet.com/api/v1/partner',
    auth: 'apikey',
    apiKeyHeader: 'x-api-key',
    amountUnit: 'cents',
    endpoints: { createCharge: '/collect-from-user', checkCharge: '/transaction/{id}' },
    bodyTemplate: ({ amount, description }) => ({ amount: Math.round(amount * 100), description }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey', 'secretKey'],
  },
  freepay: {
    name: 'Freepay',
    baseUrl: 'https://api.freepaybrasil.com',
    auth: 'basic',
    amountUnit: 'cents',
    endpoints: { createCharge: '/v1/payment-transaction/create', checkCharge: '/v1/payment-transaction/{id}' },
    bodyTemplate: ({ amount, description, customerName, customerEmail }) => ({
      amount: Math.round(amount * 100),
      payment_method: 'pix',
      customer: {
        name: customerName || 'Cliente',
        email: customerEmail || 'cliente@email.com',
        document: { number: '00000000000', type: 'cpf' },
        phone: '11999999999',
      },
      items: [{ title: description || 'Produto', unit_price: Math.round(amount * 100), quantity: 1, tangible: false }],
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: '', qrCodeText: 'pix_code', status: 'status' },
    credentials: ['apiKey', 'secretKey'],
  },
  amplopay: {
    name: 'AmploPay',
    baseUrl: 'https://api.amplopay.com.br/v1',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  tribopay: {
    name: 'TriboPay',
    baseUrl: 'https://api.tribopay.com.br/api/public/v1',
    auth: 'apikey',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey'],
  },
  atomopay: {
    name: 'AtomoPay',
    baseUrl: 'https://api.atomopay.com.br/v1',
    auth: 'apikey',
    amountUnit: 'cents',
    endpoints: { createCharge: '/charges', checkCharge: '/charges/{id}' },
    bodyTemplate: ({ amount, description }) => ({ amount: Math.round(amount * 100), description }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey'],
  },
  ironpay: {
    name: 'IronPay',
    baseUrl: 'https://api.ironpayapp.com.br/api/public/v1',
    auth: 'apikey',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey'],
  },
  wiinpay: {
    name: 'WiinPay',
    baseUrl: 'https://api.wiinpay.com.br/v1',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  nxgate: {
    name: 'NXGate',
    baseUrl: 'https://api.nxgate.com.br',
    auth: 'oauth2',
    amountUnit: 'real',
    endpoints: { createCharge: '/pix/generate', checkCharge: '/transaction/cash-in/{id}' },
    bodyTemplate: ({ amount, description, customerName }) => ({
      valor: amount,
      nome_pagador: customerName || 'Cliente',
      documento_pagador: '00000000000',
      descricao: description || 'Compra Zeze',
      webhook: '',
    }),
    responseMapping: { paymentId: 'idTransaction', qrCodeDataUrl: 'paymentCodeBase64', qrCodeText: 'paymentCode', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  axenpay: {
    name: 'AxenPay',
    baseUrl: 'https://api.axiopay.com.br/v1',
    auth: 'bearer',
    amountUnit: 'cents',
    endpoints: { createCharge: '/charges', checkCharge: '/charges/{id}' },
    bodyTemplate: ({ amount, description, customerName, customerEmail }) => ({
      amount: Math.round(amount * 100),
      method: 'pix',
      description,
      customer: { name: customerName || 'Cliente', email: customerEmail || 'cliente@email.com' },
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['token'],
  },
  veopag: {
    name: 'VeoPag',
    baseUrl: 'https://api.veopag.com/v1',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  mercadopagopix: {
    name: 'Mercado Pago PIX',
    baseUrl: 'https://api.mercadopago.com',
    auth: 'bearer',
    amountUnit: 'real',
    endpoints: { createCharge: '/v1/payments', checkCharge: '/v1/payments/{id}' },
    bodyTemplate: ({ amount, description, customerEmail, customerName }) => ({
      transaction_amount: amount,
      description,
      payment_method_id: 'pix',
      payer: { email: customerEmail || 'cliente@email.com', first_name: customerName || 'Cliente' },
    }),
    responseMapping: {
      paymentId: 'id',
      qrCodeDataUrl: 'point_of_interaction.transaction_data.qr_code_base64',
      qrCodeText: 'point_of_interaction.transaction_data.qr_code',
      status: 'status',
    },
    credentials: ['token'],
  },
  mercadopagocartao: {
    name: 'Mercado Pago Cartão',
    baseUrl: 'https://api.mercadopago.com',
    auth: 'bearer',
    amountUnit: 'real',
    endpoints: { createCharge: '/v1/payments', checkCharge: '/v1/payments/{id}' },
    bodyTemplate: ({ amount, description, customerEmail }) => ({
      transaction_amount: amount,
      description,
      installments: 1,
      payment_method_id: 'visa',
      payer: { email: customerEmail || 'cliente@email.com' },
    }),
    credentials: ['token'],
  },
  pixgateip: {
    name: 'PixGateIP',
    baseUrl: 'https://api.pixgateip.com/v1',
    auth: 'apikey',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/charge', checkCharge: '/pix/charge/{id}' },
    bodyTemplate: ({ amount }) => ({ amount: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['apiKey'],
  },
  duck: {
    name: 'Duck',
    baseUrl: 'https://api.duckpay.com.br/v1',
    auth: 'oauth2',
    amountUnit: 'cents',
    endpoints: { createCharge: '/pix/cobranca', checkCharge: '/pix/cobranca/{id}' },
    bodyTemplate: ({ amount }) => ({ valor: Math.round(amount * 100) }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'qr_code_base64', qrCodeText: 'qr_code', status: 'status' },
    credentials: ['clientId', 'clientSecret'],
  },
  bestfy: {
    name: 'Bestfy',
    baseUrl: 'https://api.bestfybr.com.br/v1',
    auth: 'apikey',
    apiKeyHeader: 'x-api-key',
    amountUnit: 'cents',
    endpoints: { createCharge: '/checkouts', checkCharge: '/checkouts/{id}' },
    bodyTemplate: ({ amount, description, webhookUrl }) => ({
      amount: Math.round(amount * 100),
      description: description || '',
      postbackUrl: webhookUrl || '',
      settings: { pix: { enabled: true, expiresInDays: 2 } },
      items: [{ title: description || 'Produto', unit_price: Math.round(amount * 100), quantity: 1, tangible: false }],
    }),
    responseMapping: { paymentId: 'id', qrCodeDataUrl: 'data.transaction.pix.qrCodeBase64', qrCodeText: 'data.transaction.pix.qrCode', status: 'status' },
    credentials: ['apiKey', 'secretKey'],
  },
  stripe: {
    name: 'Stripe',
    baseUrl: 'https://api.stripe.com/v1',
    auth: 'bearer',
    amountUnit: 'cents',
    createMethod: 'POST',
    endpoints: { createCharge: '/payment_intents', checkCharge: '/payment_intents/{id}' },
    bodyTemplate: ({ amount, description, customerEmail }) => {
      const params = new URLSearchParams({
        amount: String(Math.round(amount * 100)),
        currency: 'brl',
        'payment_method_types[]': 'pix',
        description: description || '',
      });
      if (customerEmail) params.append('receipt_email', customerEmail);
      return { _raw: params.toString(), _contentType: 'application/x-www-form-urlencoded' };
    },
    responseMapping: {
      paymentId: 'id',
      qrCodeDataUrl: 'next_action.pix_display_details.image_url_png',
      qrCodeText: 'next_action.pix_display_details.qr_code',
      status: 'status',
    },
    credentials: ['secretKey'],
  },
};

export default gatewayConfigs;
